package entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "localmusic".
 */
public class MusicInfo implements Serializable{
    private int musicId;
    private String musicName;
    private String musicPath;
    private int musicicon;

    public MusicInfo() {
    }

    public MusicInfo(int musicId, String musicName, String musicPath, int musicicon) {
        this.musicId = musicId;
        this.musicName = musicName;
        this.musicPath = musicPath;
        this.musicicon = musicicon;
    }

    public String getMusicName() {
        return musicName;
    }

    public void setMusicName(String musicName) {
        this.musicName = musicName;
    }

    public String getMusicPath() {
        return musicPath;
    }

    public void setMusicPath(String musicPath) {
        this.musicPath = musicPath;
    }

    public int getMusicicon() {
        return musicicon;
    }

    public void setMusicicon(int musicicon) {
        this.musicicon = musicicon;
    }

    public int getMusicId() {
        return musicId;
    }

    public void setMusicId(int musicId) {
        this.musicId = musicId;
    }
}
